name: ci-master-pr

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        mkdir -p bin
        echo 123 > bin/mybin
    - uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: |
          bin/*

  update-draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - id: release-drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "${{ steps.release-drafter.outputs.body }}"

  release:
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Drafts your next Release notes as Pull Requests are merged into "master"
    - id: release-drafter
      uses: release-drafter/release-drafter@v5
      with:
        config-name: release-drafter.yml
        publish: false
        name: ${{ github.ref_name }}
        tag: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/download-artifact@v3
      with:
        name: binaries
        path: |
          bin
    - uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body: ${{ steps.release-drafter.outputs.body }}
        files: |
          bin/*

  github-example-tags:
    runs-on: ubuntu-latest
    steps:
     - name: GitHub Tag Name example
       run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
