name: ci-master-pr

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
    - run:
        set -a
        ./build.sh
        ./test.sh
