name: test-pwsh

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        pwsh -version
    - name: Prep
      run: |
        # Get 'ref-name' from 'refs/heads/ref-name'
        REF=$( echo "${GITHUB_REF}" | rev | cut -d '/' -f 1 | rev )

        # Strip of 'v' prefix from tag
        MODULE_VERSION=$( echo "${REF}" | sed 's/^v*//' )

        # Pass variables to next step
        echo "REF=$REF" >> $GITHUB_ENV
        echo "MODULE_VERSION=$MODULE_VERSION" >> $GITHUB_ENV
    - name: Publish
      env:
        REF: ${{ env.REF }}
        MODULE_VERSION: ${{ env.MODULE_VERSION }}
      run: |
        echo "REF=$REF"
        echo "MODULE_VERSION=$MODULE_VERSION"
