name: test-shell

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run:
        set -a
        echo 1
        ./build.sh
        ./test.sh
