name: test-pwsh

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  test-powershell-5-1-windows-2022:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - name: Powershell version
      shell: powershell
      run: |
        $PSVersionTable
    - name: List modules 1
      shell: powershell
      run: |
        Get-Module -ListAvailable
    - name: List modules 2
      shell: powershell
      run: |
        Get-InstalledModule

  test-powershell-5-1-windows-2019:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - name: Powershell version
      shell: powershell
      run: |
        $PSVersionTable
    - name: List modules 1
      shell: powershell
      run: |
        Get-Module -ListAvailable
    - name: List modules 2
      shell: powershell
      run: |
        Get-InstalledModule

  ##########
  # Docker #
  ##########
  # Get powershell tags: https://mcr.microsoft.com/v2/powershell/tags/list
  test-powershell-6-0:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/powershell:6.0.4-ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: List Modules 1
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command 'Get-Module -ListAvailable'
    - name: List Modules 2
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command 'Get-InstalledModule'

  test-powershell-6-1:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/powershell:6.1.3-ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: List Modules 1
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command 'Get-Module -ListAvailable'
    - name: List Modules 2
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command 'Get-InstalledModule'

  test-powershell-6-2:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/powershell:6.2.4-ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: List Modules 1
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command 'Get-Module -ListAvailable'
    - name: List Modules 2
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command 'Get-InstalledModule'

  test-powershell-7-0:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/powershell:7.0.3-ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: List Modules 1
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command 'Get-Module -ListAvailable'
    - name: List Modules 2
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command 'Get-InstalledModule'

  test-powershell-7-1:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/powershell:7.1.5-ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: List Modules 1
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command 'Get-Module -ListAvailable'
    - name: List Modules 2
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command 'Get-InstalledModule'

  test-powershell-7-2:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/powershell:7.2-ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: List Modules 1
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command 'Get-Module -ListAvailable'
    - name: List Modules 2
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command 'Get-InstalledModule'

  test-powershell-7-3:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/powershell:7.3-ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: List Modules 1
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command 'Get-Module -ListAvailable'
    - name: List Modules 2
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command 'Get-InstalledModule'

  test-powershell-7-4:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/powershell:7.4-ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: List Modules 1
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command 'Get-Module -ListAvailable'
    - name: List Modules 2
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command 'Get-InstalledModule'
