name: test-shell

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  shell:
    runs-on: ubuntu-20.04
    steps:
    - name: Test
      run: |
        set -eu
        echo 1
        ./build.sh
        ./test.sh
    - name: Test
      run: |
        echo Hello world
