name: test-shell

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: |
        set -eu
        ./build.sh
        ./test.sh
    - name: Test
      run: |
        echo Hello world
