name: test-git

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: GitHub Ref and Tag example
        run: |
          set -x
          git branch --show-current || true
          git rev-parse --short HEAD || true
          git describe --tags --exact-match || true
          git describe --tags --dirty
          git name-rev --name-only $( git rev-parse --short HEAD )"
